outdir: ${oc.env:AFRAME_ONLINE_OUTDIR}
datadir: ${oc.env:ONLINE_DATADIR}
background_path: ${oc.env:ONLINE_BACKGROUND_FILE}
foreground_path: ${oc.env:ONLINE_FOREGROUND_FILE}
rejected_path: ${oc.env:ONLINE_REJECTED_FILE}
aframe_weights: ${oc.env:AFRAME_WEIGHTS}
amplfi_hl_architecture: 
  class_path: amplfi.train.architectures.flows.NSF
  init_args:
    hidden_features: [512, 512, 512]
    transforms: 20
    randperm: true
    embedding_net: 
      class_path: amplfi.train.architectures.embeddings.MultiModalPsd
      init_args:
        num_ifos: 2
        time_context_dim: 12
        freq_context_dim: 32
        time_layers: [5, 3, 3]
        freq_layers: [5, 3, 3]
        norm_layer:
          class_path: ml4gw.nn.norm.GroupNorm1DGetter
          init_args:
            groups: 8
amplfi_hlv_architecture: 
  class_path: amplfi.train.architectures.flows.NSF
  init_args:
    hidden_features: [512, 512, 512, 512, 512]
    transforms: 20
    randperm: true
    embedding_net: 
      class_path: amplfi.train.architectures.embeddings.MultiModalPsdEmbeddingWithDecimator
      init_args:
        num_ifos: 3
        time_context_dim: 20
        freq_context_dim: 48
        strain_sample_rate: ${sample_rate}
        decimator_schedule: [[0, 10, 256], [10, 28, 512], [28, 30, 2048]]
        time_kernel_size: 5
        freq_kernel_size: 3
        time_layers: [5, 3, 3]
        freq_layers: [5, 3, 3]
        norm_layer:
          class_path: ml4gw.nn.norm.GroupNorm1DGetter
          init_args:
            groups: 8
amplfi_hl_weights: ${oc.env:AMPLFI_HL_WEIGHTS}
amplfi_hlv_weights: ${oc.env:AMPLFI_HLV_WEIGHTS}
amplfi_parameter_sampler: ./prior.yaml
channels: ["H1:GDS-CALIB_STRAIN_INJ1_O3Replay", "L1:GDS-CALIB_STRAIN_INJ1_O3Replay", "V1:Hrec_hoft_16384Hz_INJ1_O3Replay"]
state_channels: ["H1:GDS-CALIB_STATE_VECTOR", "L1:GDS-CALIB_STATE_VECTOR", "V1:DQ_ANALYSIS_STATE_VECTOR"]
data_source: "frames"
sample_rate: 2048
astro_event_rate: 89
kernel_length: 20
online_inference_rate: 512
offline_inference_rate: 16
schedule: [[0, 16, 512], [16, 20, 2048]]
split: True
q: 45.6
spectrogram: [64, 128]
inference_params: ["chirp_mass", "mass_ratio", "luminosity_distance", "phic", "inclination", "dec", "psi", "phi"]
psd_length: 64
amplfi_psd_length: 10
aframe_right_pad: 0.0
fduration: 2
amplfi_fduration: 2
integration_window_length: 1
amplfi_kernel_length: 30
event_position: 29.5
fftlength: 2
highpass: 32
amplfi_highpass: 25
lowpass: null
refractory_period: 8
far_threshold: 12 # per day
email_far_threshold: 0.00000001 # Hz
emails: null
nside: 64
min_samples_per_pix: 5
server: "local"
auth_refresh: 300
ifo_suffix: "O3ReplayMDC"
input_buffer_length: 100
output_buffer_length: 16
device: "cuda"
verbose: true
