# define filters for file changes
# to trigger unit tests

# filter for changes
# to workflow
workflow: &workflow
  - '.github/filters.yaml'
  - '.github/workflows/ci-tests.yaml'


# use paths for filter names 
# for simplicity in ci-test.yaml

# cleaner way to run all jobs
# if workflow file is changed?

# libraries
libs/architectures/:
  - *workflow
  - 'libs/architectures/**'
  - 'ml4gw/**'
libs/analysis:
  - *workflow
  - 'libs/analysis/**'
  - 'libs/priors/**'
libs/trainer/:
  - *workflow
  - 'libs/trainer/**'
  - 'libs/architectures/**'
  - 'libs/logging/**'
libs/priors:
  - *workflow
  - '/libs/priors/**'

# projects
projects/sandbox/export/:
  - *workflow 
  - 'projects/sandbox/export/**'
  - 'libs/architectures/**'
  - 'libs/logging/**'
  - 'ml4gw/**'
  - 'hermes/hermes/hermes.quiver/**'

projects/sandbox/datagen/:
  - *workflow
  - 'projects/sandbox/datagen/**'
  - 'libs/logging/**'
  - 'libs/analysis/**'
  - 'libs/deploy/**'
  - 'libs/priors/**'
  - 'ml4gw/**'

projects/sandbox/infer/:
  - *workflow
  - 'projects/sandbox/infer/**'
  - 'hermes/hermes/hermes.stillwater/**'
  - 'hermes/hermes/hermes.aerial/**'
  - 'libs/analysis/**'
  - 'libs/deploy/**'
  - 'libs/logging/**'

projects/sandbox/train/:
  - *workflow
  - 'projects/sandbox/train/**'
  - 'libs/trainer/**'
  - 'libs/logging/**'
  - 'ml4gw/**'
