# define filters for file changes
# to trigger unit tests

# filter for changes
# to workflow
workflow: &workflow
  - '.github/filters.yaml'
  - '.github/workflows/ci-tests.yaml'


# use paths for filter names 
# for simplicity in ci-test.yaml

# cleaner way to run all jobs
# if workflow file is changed?

# libraries
libs/architectures/:
  - *workflow
  - 'libs/architectures/**'
  - 'ml4gw/**'

libs/ledger:
  - *workflow
  - 'libs/ledger/**'

libs/priors:
  - *workflow
  - '/libs/priors/**'
