workflow: &workflow
  - '.github/lib-filters.yaml'
  - '.github/workflows/lib-tests.yaml'

data:
  - *workflow
  - 'projects/data/**'
  - 'ml4gw/**'
  - 'libs/ledger/**'
  - 'libs/priors/**'

infer:
  - *workflow
  - 'projects/infer/**'
  - 'hermes/**'
  - 'libs/ledger/**'
  
train:
  - *workflow
  - 'projects/train/**'
  - 'ml4gw/**'
  - 'libs/ledger/**'
  - 'libs/architectures/**'

export:
  - *workflow
  - 'projects/export/**'
  - 'ml4gw/**'
  - 'hermes/**'

online:
  - *workflow
  - 'projects/online/**'
  - 'libs/ledger/**'
  - 'libs/architectures/**'
  - 'amplfi/amplfi/architectures/**'
