workflow: &workflow
  - '.github/project-filters.yaml'
  - '.github/workflows/project-build-test.yaml'
  - 'container_templates/**'
  - 'scripts/build_containers.py'
  - 'pyproject.toml'
  - 'uv.lock'

data:
  - *workflow
  - 'projects/data/**'
  - 'libs/ledger/**'
  - 'libs/priors/**'
  - 'libs/utils/**'

export:
  - *workflow
  - 'projects/export/**'
  - 'libs/utils/**'

infer:
  - *workflow
  - 'projects/infer/**'
  - 'libs/ledger/**'
  - 'libs/utils/**'
  
online:
  - *workflow
  - 'projects/online/**'
  - 'libs/architectures/**'
  - 'libs/ledger/**'
  - 'libs/p_astro/**'
  - 'libs/utils/**'
  - 'amplfi/amplfi/architectures/**'

plots:
  - *workflow
  - 'projects/plots/**'
  - 'libs/ledger/**'
  - 'libs/priors/**'
  - 'libs/utils/**'
    
train:
  - *workflow
  - 'projects/train/**'
  - 'libs/ledger/**'
  - 'libs/architectures/**'
  - 'libs/utils/**'
