workflow: &workflow
  - '.github/lib-filters.yaml'
  - '.github/workflows/lib-tests.yaml'

data:
  - *workflow
  - 'projects/data/**'
  - 'libs/ledger/**'
  - 'libs/priors/**'
  - 'libs/utils/**'
  - 'hermes/**'

infer:
  - *workflow
  - 'projects/infer/**'
  - 'hermes/**'
  - 'libs/ledger/**'
  - 'libs/utils/**'
  
train:
  - *workflow
  - 'projects/train/**'
  - 'libs/ledger/**'
  - 'libs/architectures/**'
  - 'libs/utils/**'

export:
  - *workflow
  - 'projects/export/**'
  - 'hermes/**'
  - 'libs/utils/**'

plots:
  - *workflow
  - 'projects/plots/**'
  - 'libs/utils/**'
  - 'libs/ledger/**'
  - 'libs/priors/**'
  - 'hermes/**'

online:
  - *workflow
  - 'projects/online/**'
  - 'libs/ledger/**'
  - 'libs/architectures/**'
  - 'libs/utils/**'
  - 'libs/p_astro/**'
  - 'amplfi/amplfi/architectures/**'
