workflow: &workflow
  - '.github/lib-filters.yaml'
  - '.github/workflows/lib-tests.yaml'

projects/data/:
  - *workflow
  - 'projects/data/**'
  - 'ml4gw/**'
  - 'libs/ledger/**'
  - 'libs/priors/**'
