repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.0
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version
  rev: 0.9.30
  hooks:
    - id: uv-lock
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: end-of-file-fixer
  - id: check-yaml
    exclude: ^charts/raycluster/templates/
- repo: https://github.com/snakemake/snakefmt
  rev: v2.0.1
  hooks:
    - id: snakefmt
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.15
  hooks:
    - id: helmlint
- repo: local
  hooks:
    - id: conda-lock
      name: conda-lock
      entry: python scripts/conda_relock.py
      language: python
      additional_dependencies: ["conda-lock>=4"]
      files: ^(pipeline/envs/snakemake|projects/data/data|projects/online/online)\.(yaml|conda-lock\.yml)$
