[project]
name = "infer"
version = "0.0.1"
description = ""
authors = [
    { name = "Alec Gunny" },
    { name = "Ethan Marx" },
    { name = "Will Benoit" },
]
requires-python = ">=3.11,<3.14"
dependencies = [
    "jsonargparse[signatures]>=4.29,<5",
    "tqdm~=4.66",
    "psutil>=5.9",
    "torch==2.10.0",
    "ml4gw-hermes[torch]",
    "utils[torch]",
    "ledger",
    "gwpy>=4.0,<5",
    "h5py>=3.10,<4",
    "numpy>=2",
]

[project.scripts]
infer-triton = "infer.cli:main_triton"
infer-local = "infer.cli:main_local"
start-server = "infer.server:main"

[dependency-groups]
test = ["pytest>=8,<9"]
dev = [{ include-group = "test" }, "jupyter>=1.0.0,<2"]

[tool.uv]

[tool.uv.sources]
utils = { workspace = true }
ledger = { workspace = true }
# TODO: point at released version once available
ml4gw-hermes = { git = "https://github.com/ML4GW/hermes", branch = "dev" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
