[project]
name = "priors"
version = "0.1.0"
description = "Priors used for aframe analysis"
authors = [{ name = "Ethan Jacob Marx", email = "ethan.marx@ligo.org" }]
requires-python = ">=3.11,<3.14"
license = "MIT"
dependencies = [
    "astropy>=6.0",
    "bilby>=2.2.2,<3",
    "numpy>=2",
    "utils",
]

[dependency-groups]
test = ["pytest>=8.2,<9"]
dev = [{ include-group = "test" }, "jupyter>=1.0.0,<2"]

[tool.uv]

[tool.uv.sources]
utils = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
