[project]
name = "train"
version = "0.1.0"
description = "Train aframe"
authors = [
    { name = "Ethan Marx", email = "ethan.marx@ligo.org" },
    { name = "Alec Gunny", email = "alecg@mit.edu" },
    { name = "Will Benoit", email = "benoit090@umn.edu" },
]
requires-python = ">=3.11,<3.14"
readme = "README.md"
license = "MIT"
dependencies = [
    "torchmetrics>=1.0,<2",
    "torch==2.10.0",
    "lightning>=2.2.1",
    "jsonargparse[signatures]>=4.49,<5",
    "wandb>=0.15",
    "ray[default, tune]>=2.8.0,<3",
    "lightray>=0.2.3",
    "boto3~=1.30",
    "botocore",
    "fsspec[s3]>=2024",
    "s3fs>=2024",
    "utils[torch]",
    "ml4gw>=0.8.4",
    "ledger",
    "architectures",
    "filelock>=3.13.1,<5",
    "h5py>=3.10,<4",
    "numpy>=2",
    "kr8s>=0.20.0",
    "anyio",
]

[project.scripts]
train = "train.cli:main"
train-remote = "train.remote:main"

[dependency-groups]
test = ["pytest>=8.2,<9"]
dev = [{ include-group = "test" }, "jupyter>=1.0.0,<2"]

[tool.uv]

[tool.uv.sources]
utils = { workspace = true }
ledger = { workspace = true }
architectures = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
