# default prior for use with `IMRPhenomPv2`
class_path: train.prior.AframePrior
init_args:
  conversion_function: train.conversion.precessing_to_lalsimulation_parameters
  priors:
    chirp_mass: 
      class_path: torch.distributions.Uniform
      init_args:
        low: 5
        high: 250
        validate_args: false
    mass_ratio: 
      class_path: torch.distributions.Uniform
      init_args:
        low: 0.05 
        high: 0.999
        validate_args: false
    distance: 
      class_path: ml4gw.distributions.UniformComovingVolume
      init_args:
        minimum:  0 
        maximum: 2
        distance_type: redshift
        validate_args: false
    inclination: 
      class_path: ml4gw.distributions.Sine
      init_args:
        low: 0 
        high: 3.14159 
        validate_args: false
    phic: 
      class_path: torch.distributions.Uniform
      init_args:
        low: 0.0 
        high: 6.28318 
        validate_args: false
    a_1: 
      class_path: torch.distributions.Uniform
      init_args:
        low: 0.0 
        high: 0.999
        validate_args: false
    a_2: 
      class_path: torch.distributions.Uniform
      init_args:
        low: 0.0 
        high: 0.999
        validate_args: false
    tilt_1: 
      class_path: torch.distributions.Uniform
      init_args:
        low: 0.0 
        high: 3.14159  
        validate_args: false
    tilt_2: 
      class_path: torch.distributions.Uniform
      init_args:
        low: 0.0 
        high: 3.14159 
        validate_args: false
    phi_jl: 
      class_path: torch.distributions.Uniform
      init_args:
        low: 0.0 
        high: 6.28318 
        validate_args: false
    phi_12: 
      class_path: torch.distributions.Uniform
      init_args:
        low: 0.0
        high: 6.28318 
        validate_args: false
