# commented args (i.e. comments with colon at end 
# to illustrate a value needs to be filled out)
# represent values filled out
# by the export task at run time. To build a functional
# standalone config, add these in yourself.

# logfile: 
# weights: 
# batch_file: 
# repository_directory: 
num_ifos: 2
kernel_length: 1.5
inference_sampling_rate: 4
sample_rate: 2048
batch_size: 128
fduration: 1
psd_length: 64
preprocessor:
  class_path: utils.preprocessing.BatchWhitener
  init_args:
    kernel_length: 1.5
    sample_rate: 2048
    inference_sampling_rate: 4
    batch_size: 128
    fduration: 1
    fftlength: 2
    highpass: 32
streams_per_gpu: 6
aframe_instances: 1
platform: TENSORRT
clean: false
verbose: false
