apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-head-loadbalancer
spec:
  ports:
  - name: client
    port: 10001
    protocol: TCP
    targetPort: 10001
  selector:
    app: {{ .Chart.Name }}-head
  type: LoadBalancer
