{{- if .Values.dev }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-git-creds
type: Opaque
data:
  ssh: {{ .Files.Get "id_rsa" | b64enc }}
  known_hosts: {{ .Values.gitRepo.known_hosts | quote | b64enc | indent 2 }}
{{- end }}
