[project]
name = "data"
version = "0.0.1"
description = "aframe data generation scripts"
authors = [
    { name = "Alec Gunny", email = "alecg@mit.edu" },
    { name = "Ethan Marx", email = "emarx@mit.edu" },
]
requires-python = ">=3.11,<3.14"
license = "MIT"
dependencies = [
    "utils",
    "ledger[generation]",
    "priors",
    "numpy>=2",
    "gwpy>=4.0,<5",
    "jsonargparse[signatures]>=4.29,<5",
]

# Create two dependency groups to allow the splitting
# described in the root-level pyproject.toml
[project.optional-dependencies]
# torchaudio comes in through ml4gw, but is listed so that it can be pinned to
# the same index as torch below
cpu = ["torch", "torchaudio", "ml4gw>=0.7.2"]
cuda = ["torch", "torchaudio", "ml4gw>=0.7.2"]

[project.scripts]
fetch-data = "data.fetch.cli:main"
generate-segments = "data.segments.cli:main"
generate-training-waveforms = "data.waveforms.cli:training"
generate-testing-waveforms = "data.waveforms.cli:testing"
generate-validation-waveforms = "data.waveforms.cli:validation"

[dependency-groups]
test = ["pytest>=8.2.1,<9"]
dev = [{ include-group = "test" }, "jupyter>=1.0.0,<2"]

[tool.uv]


[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cpu", extra = "cpu" }]
torchaudio = [{ index = "pytorch-cpu", extra = "cpu" }]
utils = { workspace = true }
ledger = { workspace = true }
priors = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
